name: CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      NODE_ENV: production

    environment:
      name: Production
      url: https://portfolio.francomarino.dev/

    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel (Production)
        run: |
          npm install -g vercel
          vercel --prod --token=$VERCEL_TOKEN --yes
