name: CI Pipeline

on:
  push:
    branches: [master]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (22)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Upload Playwright report (artifact)
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Prepare test results for Pages
        if: ${{ always() }}
        run: |
          mkdir -p dist/test-results
          cp -r playwright-report/* dist/test-results/

      - name: Upload Pages artifact (test results)
        if: ${{ always() }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy-results:
    needs: lint-test
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      deployments: write
      contents: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        if: ${{ always() }}
        id: deployment
        uses: actions/deploy-pages@v4
