name: Preview environment

on:
  pull_request:
    branches: [master]

jobs:
  deploy-preview-vercel:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      NODE_ENV: production

    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Deployment Preview
        id: create_deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: Preview
          description: Deploy preview to Vercel via CLI
          transient-environment: true
          production-environment: false
          initial-status: pending
          auto-merge: false
          task: deploy

      - name: Deploy preview to Vercel
        id: vercel_deploy
        run: |
          npm install -g vercel
          url=$(vercel --token=$VERCEL_TOKEN --prod=false --confirm | tail -n1)
          echo "preview_url=$url" >> $GITHUB_OUTPUT
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Update deployment preview status
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment-id: ${{ steps.create_deployment.outputs.deployment_id }}
          state: success
          environment-url: ${{ steps.vercel_deploy.outputs.preview_url }}
